version: '3'
services:
  delivery-db:
    container_name: delivery-db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=delivery-db
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
  delivery-app:
    build:
      context: ./
    ports:
        - 8000:8000